service: grap-dyn-bcrjwt
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  environment:
    DYNAMODB_TABLE: Users
  iamRoleStatements:
    - Effect: Allow
      Action: dynamodb:*
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"


package:
  individually: true

plugins:
  - serverless-offline
  - serverless-dynamodb-local
  - serverless-plugin-typescript

custom:
  serverless-offline:
    httpPort: 3000
  dynamodb:
    start:
      port: 8000
      inMemory: true

functions:
  graphql:
    handler: src/app.graphqlHandler
    events:
      - http:
          path: /graphql
          method: post
          cors: true

resources:
  Resources:
    Users:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH

